title: cnctdadots
author: cnctdadots
email: your-email@example.com
description: >- 
  Welcome to my personal website and blog where I share my thoughts,
  experiences, and projects.

# Social links
github_username: cnctdadots
# twitter_username: your-twitter
# linkedin_username: your-linkedin

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Site settings
show_excerpts: true

# Add to your existing _config.yml
markdown: kramdown
highlighter: rouge

# Additional settings
show_excerpts: true
google_analytics: # your GA tag here if you want analytics

# Collections
collections:
  projects:
    output: true
    permalink: /projects/:path/

# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: true
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "project"
